services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./config/.env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    env_file:
      - ./config/.env
    image: postgres:17.4-alpine3.21
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2-alpine3.21
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redisdata:/data

  # prometheus:
  #   image: prom/prometheus
  #   ports:
  #     - "9000:9090"
  #   volumes:
  #     - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   restart: always

volumes:
  pgdata:
  redisdata:
